#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 21/05/2021

# Description: 
# Creates a backup tar file in folder given as 2nd arguement for all the files present in the directory given in 1st arguement

# Usage: 
# bash backup_script ~/work ~/backup
# Here backup of ~/work directory will be saved in ~/backup directory 

echo "Hello, ${USER^}"
echo "I will backup your $1 in $2"
currently_in=$pwd
cd $1/..
tar -cf backup_"$(date +%d-%m-%Y_%H-%M-%S).tar" $1
mv *tar $2
cd $currently_in

echo "Backup completed successfully."

# Last Modified: 22/05/2021
