#!/bin/bash

# Author: Hemant Sachdeva <hemant.evolver@gmail.com>
# Date Created: 08/06/2021

# Description:
# Adds/Subtract/Multiplies/Devides upto 10 Positional parameters
# where 1st parameter is always the operator and the default parameter
# is given as 0 to the undefined parameters (take care when dividing <9 numbers)

# Uage:
# bash calculator + 5 6 8 9 

echo $(( ${2:-0} $1 ${3:-0} $1 ${4:-0} $1 ${5:-0} $1 ${6:-0} $1 ${7:-0} $1 ${8:-0} $1 ${9:-0} ))

# Last Modified: 08/06/2021
