#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 08/06/2021

# Description:
# Adds/Subtract/Multiplies/Devides upto 10 Positional parameters
# where 1st parameter is always the operator and the default parameter
# is given as 0 to the undefined parameters (take care when dividing <9 numbers)

# Uage:
# bash calculator + 5 6 8 9 

echo $(( ${2:-0} $1 ${3:-0} $1 ${4:-0} $1 ${5:-0} $1 ${6:-0} $1 ${7:-0} $1 ${8:-0} $1 ${9:-0} ))

# Last Modified: 08/06/2021
