#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 12/06/2021

read -rp "How many number of terms to be generated: " n

function fib {
    x=0
    y=1
    i=2
    echo "Fibonacci Series up to $n terms: "
    echo "$x"
    echo "$y"
    while [ $i -lt $n ]; do
        i=$(expr $i + 1)
        z=$(expr $x + $y)
        echo "$z"
        x=$y
        y=$z
    done
}
r=$(fib $n)
echo "$r"

# Last Modified: 12/06/2021
