#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 28/06/2021

read -p "What is your first name?: " firstname
read -p "What is your surname/family name?: " lastname

PS3="Which phone you are comfortable with?: "
select phone in handheld headset;
do
    echo "You selected $phone phone."
    echo
    read -p "Is it correct?[y|n]: " option
    case $option in
    Y | y) echo "Okay thanks for confirming."
            break ;;
    esac
done
PS3="In which department do you work?: "
select department in finance sales "customer service" engineering;
do
    echo "You selected $department."
    read -p "Is it correct?[y|n]: " option
    case $option in
    Y | y) echo "Okay thanks for confirming."
            break ;;
    esac
done
echo "Note: Your extension number and access code must both be exactly 4 digits long."
read -n 4 -p "What is your extension numbers?: " extension
echo ""
read -n 4 -s -p "What access code would you like to use when dialing in?: " access

echo
echo "Thanks!!"

echo "$firstname,$lastname,$phone,$department,$extension,$access" >> extensions.csv

# Last Modified: 28/06/2021
