#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 12/06/2021

read -rp "Enter first number: " num1
read -rp "Enter second number: " num2
read -rp "Enter third number: " num3

if [ $num1 -gt $num2 ] && [ $num1 -gt $num3 ]; then
        echo "$num1 is gtreatest among all."
elif [ $num2 -gt $num3 ] && [ $num2 -gt $num1 ]; then
        echo "$num2 is greatest among all."
else
    echo "$num3 is greatest among all."
fi

# Last Modified: 12/06/2021
