#!/bin/bash

# Author: Hemant Sachdeva <hemant.evolver@gmail.com>
# Date Created: 12/06/2021

read -rp "Enter first number: " num1
read -rp "Enter second number: " num2
read -rp "Enter third number: " num3

if [ $num1 -gt $num2 ] && [ $num1 -gt $num3 ]; then
        echo "$num1 is gtreatest among all."
elif [ $num2 -gt $num3 ] && [ $num2 -gt $num1 ]; then
        echo "$num2 is greatest among all."
else
    echo "$num3 is greatest among all."
fi

# Last Modified: 12/06/2021
