#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 03/07/2021

PS3="Select a city from above to travel: "
select city in Tokyo London "Los Angeles" Moscow Dubai Manchester "New York" Paris Bangalore Johannesburg Istanbul Milan "Abu Dhabi" Pune Nairobi Berlin Karachi; do
    case $city in
    Tokyo)
        country=Japan
        ;;
    London | Manchester)
        country="United Kingdom"
        ;;
    Moscow)
        country=Russia
        ;;
    Dubai | "Abu Dhabi")
        country="United Arab Emirates"
        ;;
    Paris)
        country=France
        ;;
    Bangalore | Pune)
        country=India
        ;;
    Johannesburg)
        country="South Africa"
        ;;
    Istanbul)
        country=Turkey
        ;;
    Milan)
        country=Italy
        ;;
    Nairobi)
        country=Kenya
        ;;
    Berlin)
        country=Germany
        ;;
    Karachi)
        country=Pakistan
        ;;
    Madrid)
        country=Spain
        ;;
    esac
echo "$city is in $country"
break
done

# Last Modified: 03/07/2021
