#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 07/07/2021

readarray -t urls < urls.txt

for urls in "${urls[@]}" ; do
    curl --head "$urls" > "$(echo $urls | cut -d "." -f 2)".txt
done

# Last Modified: 07/07/2021
