#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 21/07/2021

while getopts "nf:" param; do
  case "$param" in
  f) file="$OPTARG" ;;
  n) set -x ;;
  *) echo "Invalid option" ;;
  esac
done

case "$file" in
*.tar.gz) tar xzf "$file" ;;
*.gz) gzip -d "$file" ;;
*.zip) unzip "$file" ;;
*) echo "Unknown filetype" ;;
esac

if [[ "$(uname)" == "Linux" ]]; then
  echo "Using Linux"
fi


# Last Modified: 21/07/2021
