#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 21/07/2021

if ! grep -q "backup=true.*" "$HOME/.myconfig"; then
  echo "Backup not enabled in $HOME/.myconfig, exiting"
  exit 1
fi

tar -cf "$1/my_backup_$(date +%d-%m-%Y_%H-%M-%S).tar" "$HOME"


# Last Modified: 21/07/2021
