#!/bin/bash

# Author: Hemant Sachdeva <hemant.evolver@gmail.com>
# Date Created: 21/07/2021

if ! grep -q "backup=true.*" "$HOME/.myconfig"; then
  echo "Backup not enabled in $HOME/.myconfig, exiting"
  exit 1
fi

tar -cf "$1/my_backup_$(date +%d-%m-%Y_%H-%M-%S).tar" "$HOME"


# Last Modified: 21/07/2021
