#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 07/06/2021

# Description:
# Shorten any github profile/repo/commit/blob/raw content to a custom link followed by https://git.io/
# if that custom link is available

# Usage:
# bash shorten git/url/to/be/shorten customText

# bash shorten https://github.com/HemantSachdeva HemantSachdeva
# so the shorten url will be https://git.io/HemantSachdeva

curl -i https://git.io -F "url=$1" -F "code=$2"

# Last Modified: 07/06/2021
