#!/bin/bash

#     Copyright (C) 2021 Hemant Sachdeva <hemant.evolver@gmail.com>

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Date Created: 06/07/2021

while getopts "m:s:" opt; do
    case $opt in
    m)
        total_seconds=$(( total_seconds + $(( OPTARG * 60 )) )) # OPTARG stores the flag provided in command b user
        ;;
    s)
        total_seconds=$(( total_seconds + OPTARG ))
        ;;
    *)
        echo "You have given a wrong flag. Use -m for minutes and -s for seconds"
        ;;
    esac
done

while [[ $total_seconds -ge 0 ]] ; do
    echo "$total_seconds seconds left"
    total_seconds=$(( total_seconds - 1 ))
    sleep 1s
done

echo "Time's Up!"

# Last Modified: 06/07/2021
